spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 139.199.133.171:8848
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.ley.nacos.consumer.service: debug

feign:
  hystrix:
    enabled: true




